import { FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Badge, Button, Dialog, EmptyState, Input, Skeleton } from "../../components/ui.js";
import { Client, portfolioApi } from "./api.js";

type ClientDraft = { name: string; type: "PERSON" | "COMPANY"; documentNumber: string; email: string; phone: string; financialContactName: string; financialContactEmail: string; financialContactPhone: string; notes: string };
const empty: ClientDraft = { name: "", type: "COMPANY", documentNumber: "", email: "", phone: "", financialContactName: "", financialContactEmail: "", financialContactPhone: "", notes: "" };

export function ClientsPage() {
  const [clients, setClients] = useState<Client[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Client | null>(null); const [error, setError] = useState<string | null>(null);
  const load = () => { setLoading(true); void portfolioApi.clients(query).then((result) => setClients(result?.items ?? [])).catch(() => setError("Não foi possível carregar os clientes.")).finally(() => setLoading(false)); };
  useEffect(load, [query]);
  const start = (client?: Client) => { setEditing(client ?? null); setOpen(true); };
  return <section><div className="page-heading"><div><p className="eyebrow">Financeiro</p><h1>Clientes</h1><p className="muted">Cadastro compartilhado usado por contratos e projetos.</p></div><div><Link className="ui-button ui-button-secondary" to="/finance">Voltar à carteira</Link><Button onClick={() => start()}>+ Novo cliente</Button></div></div><div className="card portfolio-card"><div className="portfolio-toolbar"><Input aria-label="Buscar clientes" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome…" /></div>{loading ? <div style={{ padding: "1rem" }}><Skeleton /><Skeleton /></div> : error ? <EmptyState title="Clientes indisponíveis" detail={error} /> : clients.length ? <div className="table-scroll"><table className="portfolio-table"><thead><tr><th>Cliente</th><th>Tipo</th><th>Email</th><th>Contato financeiro</th><th>Ações</th></tr></thead><tbody>{clients.map((client) => <tr key={client.id}><td><strong className="table-primary">{client.name}</strong><span>{client.documentNumber ?? "Documento não informado"}</span></td><td><Badge tone="neutral">{client.type === "COMPANY" ? "Pessoa jurídica" : "Pessoa física"}</Badge></td><td>{client.email ?? "—"}</td><td>{client.financialContactName ?? "—"}</td><td><Button variant="ghost" onClick={() => start(client)}>Editar</Button></td></tr>)}</tbody></table></div> : <EmptyState title="Nenhum cliente encontrado" detail="Cadastre o primeiro cliente para iniciar um contrato." />}</div>{open ? <ClientDialog client={editing} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); load(); }} /> : null}</section>;
}

function ClientDialog({ client, onClose, onSaved }: { client: Client | null; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<ClientDraft>(() => client ? { name: client.name, type: client.type, documentNumber: client.documentNumber ?? "", email: client.email ?? "", phone: client.phone ?? "", financialContactName: client.financialContactName ?? "", financialContactEmail: client.financialContactEmail ?? "", financialContactPhone: client.financialContactPhone ?? "", notes: client.notes ?? "" } : empty);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const change = (key: keyof ClientDraft, value: string) => setForm((state) => ({ ...state, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.name.trim()) return setError("Informe o nome do cliente."); setBusy(true); setError(null); try { if (client) await portfolioApi.updateClient(client.id, form); else await portfolioApi.createClient(form); onSaved(); } catch { setError("Não foi possível salvar o cliente."); } finally { setBusy(false); } };
  return <Dialog open title={client ? "Editar cliente" : "Novo cliente"} onClose={onClose}><form onSubmit={submit} className="client-dialog-form"><div className="field-grid"><label className="field field-span-2">Nome<Input required value={form.name} onChange={(event) => change("name", event.target.value)} /></label><label className="field">Tipo<select className="ui-input" value={form.type} onChange={(event) => change("type", event.target.value)}><option value="COMPANY">Pessoa jurídica</option><option value="PERSON">Pessoa física</option></select></label><label className="field">CPF/CNPJ<Input value={form.documentNumber} onChange={(event) => change("documentNumber", event.target.value)} /></label><label className="field">Email<Input type="email" value={form.email} onChange={(event) => change("email", event.target.value)} /></label><label className="field">Telefone<Input value={form.phone} onChange={(event) => change("phone", event.target.value)} /></label><label className="field field-span-2">Contato financeiro<Input value={form.financialContactName} onChange={(event) => change("financialContactName", event.target.value)} /></label><label className="field">Email financeiro<Input type="email" value={form.financialContactEmail} onChange={(event) => change("financialContactEmail", event.target.value)} /></label><label className="field">Telefone financeiro<Input value={form.financialContactPhone} onChange={(event) => change("financialContactPhone", event.target.value)} /></label><label className="field field-span-2">Observações<textarea value={form.notes} onChange={(event) => change("notes", event.target.value)} /></label></div>{error ? <p className="field-error" role="alert">{error}</p> : null}<Button disabled={busy}>{busy ? "Salvando…" : "Salvar cliente"}</Button></form></Dialog>;
}
