import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Badge, EmptyState, Input, Skeleton } from "../../components/ui.js";
import { ContractRow, brl, dateBR, portfolioApi } from "./api.js";

const filters = ["Todos", "Ativos", "Concluídos", "Pausados", "Cancelados", "Sem plano", "Em atraso", "Quitados", "Parciais"] as const;
function badgeTone(status: string): "success" | "warning" | "danger" | "neutral" { return status === "ACTIVE" || status === "COMPLETED" ? "success" : status === "PAUSED" ? "warning" : status === "CANCELLED" ? "danger" : "neutral"; }

export function ContractPortfolioPage() {
  const [items, setItems] = useState<ContractRow[]>([]); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<(typeof filters)[number]>("Todos"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let live = true; setLoading(true); void portfolioApi.contracts().then((result) => { if (live) setItems(result?.items ?? []); }).catch(() => live && setError("Não foi possível carregar a carteira de contratos.")).finally(() => live && setLoading(false)); return () => { live = false; }; }, []);
  const filtered = useMemo(() => items.filter((item) => { const text = `${item.name} ${item.client.name}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()); if (!text) return false; if (filter === "Ativos") return item.status === "ACTIVE"; if (filter === "Concluídos") return item.status === "COMPLETED"; if (filter === "Pausados") return item.status === "PAUSED"; if (filter === "Cancelados") return item.status === "CANCELLED"; if (filter === "Sem plano") return !item.hasPlan; if (filter === "Em atraso") return item.overdue !== "0.00"; if (filter === "Quitados") return item.hasPlan && item.outstanding === "0.00"; if (filter === "Parciais") return item.received !== "0.00" && item.outstanding !== "0.00"; return true; }), [filter, items, query]);
  if (loading) return <><Skeleton /><Skeleton /></>;
  if (error) return <EmptyState title="Carteira indisponível" detail={error} />;
  return <section>
    <div className="page-heading"><div><p className="eyebrow">Financeiro</p><h1>Carteira de contratos</h1><p className="muted">Contratos fechados, pagamentos e projetos conectados.</p></div><div><Link className="ui-button ui-button-secondary" to="/finance/clients">Clientes</Link><Link className="ui-button ui-button-primary" to="/finance/contracts/new">+ Novo contrato</Link></div></div>
    <div className="portfolio-kpis"><Metric label="Contratado" value={brl(items.reduce((total, item) => add(total, item.value), "0.00"))} /><Metric label="Recebido" value={brl(items.reduce((total, item) => add(total, item.received), "0.00"))} /><Metric label="A receber" value={brl(items.reduce((total, item) => add(total, item.outstanding), "0.00"))} /><Metric label="Em atraso" value={brl(items.reduce((total, item) => add(total, item.overdue), "0.00"))} tone="danger" /></div>
    <div className="card portfolio-card"><div className="portfolio-toolbar"><Input aria-label="Buscar contratos" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar contrato ou cliente…" /><div className="filter-list">{filters.map((item) => <button key={item} className={filter === item ? "filter-chip active" : "filter-chip"} onClick={() => setFilter(item)}>{item}</button>)}</div></div>
      {filtered.length === 0 ? <EmptyState title="Nenhum contrato encontrado" detail="Ajuste os filtros ou registre um contrato fechado." /> : <div className="table-scroll"><table className="portfolio-table"><thead><tr><th>Contrato</th><th>Produto</th><th>Status</th><th>Valor</th><th>Recebido</th><th>A receber</th><th>Próximo vencimento</th><th>Projeto</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><Link className="table-primary" to={`/finance/contracts/${item.id}`}>{item.name}</Link><span>{item.client.name}</span></td><td>{item.product === "OTHER" ? item.customProductName : item.product}</td><td><Badge tone={badgeTone(item.status)}>{labelStatus(item.status)}</Badge>{item.overdue !== "0.00" ? <Badge tone="danger">Em atraso</Badge> : null}</td><td>{brl(item.value)}</td><td className="amount-success">{brl(item.received)}</td><td>{brl(item.outstanding)}</td><td>{dateBR(item.nextDue)}</td><td>{item.project ? <Link to={`/projects/${item.project.id}`}>{item.project.name}</Link> : "—"}</td></tr>)}</tbody></table></div>}</div>
  </section>;
}
function Metric({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div className={`kpi ${tone ? `kpi-${tone}` : ""}`}><span className="muted">{label}</span><strong>{value}</strong></div>; }
function labelStatus(status: string) { return ({ ACTIVE: "Ativo", COMPLETED: "Concluído", PAUSED: "Pausado", CANCELLED: "Cancelado" } as Record<string, string>)[status] ?? status; }
function cents(value: string): bigint { const [whole = "0", decimals = ""] = value.split("."); return BigInt(whole) * 100n + BigInt(decimals.padEnd(2, "0").slice(0, 2)); }
function add(left: string, right: string) { const total = cents(left) + cents(right); return `${total / 100n}.${(total % 100n).toString().padStart(2, "0")}`; }
