import { FormEvent, useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Badge, Button, Dialog, EmptyState, Input, Skeleton } from "../../components/ui.js";
import { Link as ResourceLink, Project, brl, dateBR, portfolioApi } from "./api.js";

const statuses = ["NOT_STARTED", "IN_PROGRESS", "PAUSED", "DELAYED", "COMPLETED", "CANCELLED"];

export function ProjectDetailPage() {
  const { projectId = "" } = useParams();
  const [project, setProject] = useState<Project | null>(null);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => { setLoading(true); setError(null); void portfolioApi.project(projectId).then((value) => setProject(value ?? null)).catch(() => setError("Não foi possível carregar este projeto.")).finally(() => setLoading(false)); }, [projectId]);
  useEffect(load, [load]);
  if (loading) return <><Skeleton /><Skeleton /></>;
  if (!project || error) return <EmptyState title="Projeto indisponível" detail={error ?? "Este projeto não está disponível."} />;
  return <section>
    <div className="page-heading"><div><p className="eyebrow">Projetos</p><h1>{project.name}</h1><p className="muted">{project.client.name}</p></div><div><Badge tone={projectTone(project.status)}>{projectLabel(project.status)}</Badge><Button variant="secondary" onClick={() => setEditing((value) => !value)}>{editing ? "Cancelar edição" : "Editar projeto"}</Button></div></div>
    {editing ? <ProjectEdit project={project} onDone={() => { setEditing(false); load(); }} /> : <div className="detail-grid"><div className="card"><h2>Contexto</h2><dl><Row label="Cliente" value={project.client.name} /><Row label="Contrato" value={project.contract?.name ?? "Não vinculado"} /><Row label="Gerente" value={project.manager?.name ?? "Não definido"} /><Row label="Status" value={projectLabel(project.status)} /><Row label="Início" value={dateBR(project.startDate)} /><Row label="Previsão" value={dateBR(project.expectedEndDate)} /></dl>{project.contract ? <Link to={`/finance/contracts/${project.contract.id}`}>Abrir contrato 360 →</Link> : null}</div>{project.finance ? <div className="card"><h2>Resumo financeiro</h2><dl><Row label="Valor contratado" value={brl(project.finance.value)} /><Row label="Recebido" value={brl(project.finance.received)} /><Row label="A receber" value={brl(project.finance.outstanding)} /><Row label="Em atraso" value={brl(project.finance.overdue)} /><Row label="Próximo vencimento" value={dateBR(project.finance.nextDue)} /></dl></div> : null}<div className="card detail-wide"><h2>Descrição</h2><p className="detail-text">{project.description || "Nenhuma descrição cadastrada."}</p><h3>Observações internas</h3><p className="detail-text">{project.internalNotes || "Nenhuma observação interna."}</p></div></div>}
    <ProjectLinks project={project} reload={load} />
  </section>;
}

function ProjectEdit({ project, onDone }: { project: Project; onDone: () => void }) {
  const [form, setForm] = useState({ name: project.name, status: project.status, startDate: project.startDate ?? "", expectedEndDate: project.expectedEndDate ?? "", description: project.description ?? "", internalNotes: project.internalNotes ?? "" });
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const change = (key: keyof typeof form, value: string) => setForm((state) => ({ ...state, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { await portfolioApi.updateProject(project.id, { ...form, startDate: form.startDate || null, expectedEndDate: form.expectedEndDate || null }); onDone(); } catch { setError("Não foi possível salvar as alterações."); } finally { setBusy(false); } };
  return <form className="card edit-card" onSubmit={submit}><h2>Editar projeto</h2><div className="field-grid"><label className="field field-span-2">Nome<Input value={form.name} onChange={(event) => change("name", event.target.value)} /></label><label className="field">Status<select className="ui-input" value={form.status} onChange={(event) => change("status", event.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="field">Data de início<Input type="date" value={form.startDate} onChange={(event) => change("startDate", event.target.value)} /></label><label className="field">Previsão de término<Input type="date" value={form.expectedEndDate} onChange={(event) => change("expectedEndDate", event.target.value)} /></label><label className="field field-span-2">Descrição<textarea value={form.description} onChange={(event) => change("description", event.target.value)} /></label><label className="field field-span-2">Observações internas<textarea value={form.internalNotes} onChange={(event) => change("internalNotes", event.target.value)} /></label></div>{error ? <p className="field-error" role="alert">{error}</p> : null}<Button disabled={busy}>{busy ? "Salvando…" : "Salvar alterações"}</Button></form>;
}

function ProjectLinks({ project, reload }: { project: Project; reload: () => void }) {
  const blank = { type: "REPOSITORY", label: "", url: "", description: "" }; const [show, setShow] = useState(false); const [editingLink, setEditingLink] = useState<ResourceLink | null>(null); const [pendingDelete, setPendingDelete] = useState<ResourceLink | null>(null); const [busy, setBusy] = useState(false); const [form, setForm] = useState(blank);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { if (editingLink) await portfolioApi.updateLink(editingLink.id, form); else await portfolioApi.addProjectLink(project.id, form); setForm(blank); setEditingLink(null); setShow(false); reload(); } finally { setBusy(false); } };
  const edit = (link: ResourceLink) => { setEditingLink(link); setForm({ type: link.type, label: link.label, url: link.url, description: link.description ?? "" }); setShow(true); };
  const remove = async () => { if (!pendingDelete) return; setBusy(true); try { await portfolioApi.deleteLink(pendingDelete.id); setPendingDelete(null); reload(); } finally { setBusy(false); } };
  return <section className="card documents-card"><div className="section-heading"><div><h2>Links do projeto</h2><p className="muted">GitHub, Figma, Notion, produção e documentação.</p></div><Button onClick={() => { setEditingLink(null); setForm(blank); setShow(!show); }}>{show ? "Cancelar" : "+ Adicionar link"}</Button></div>{show ? <form className="link-form" onSubmit={submit}><div className="field-grid"><label className="field">Tipo<select className="ui-input" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{["REPOSITORY", "FIGMA", "NOTION", "DRIVE", "PRODUCTION", "DOCUMENTATION", "OTHER"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="field">Título<Input required value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} /></label><label className="field field-span-2">URL<Input required type="url" value={form.url} onChange={(event) => setForm({ ...form, url: event.target.value })} /></label><label className="field field-span-2">Descrição<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div><Button disabled={busy}>{busy ? "Salvando…" : editingLink ? "Salvar alterações" : "Salvar link"}</Button></form> : null}{project.links?.length ? <ul className="resource-list">{project.links.map((link) => <li key={link.id}><div><Badge tone="neutral">{link.type}</Badge><strong>{link.label}</strong>{link.description ? <span>{link.description}</span> : null}</div><div><a href={link.url} target="_blank" rel="noreferrer">Abrir ↗</a><Button variant="ghost" onClick={() => edit(link)}>Editar</Button><Button variant="ghost" onClick={() => setPendingDelete(link)}>Remover</Button></div></li>)}</ul> : <EmptyState title="Nenhum link cadastrado" detail="Adicione o repositório, protótipo ou documentação do projeto." />}{pendingDelete ? <Dialog open title="Remover link" onClose={() => setPendingDelete(null)}><p>Remover “{pendingDelete.label}”? Esta ação não pode ser desfeita.</p><Button variant="destructive" disabled={busy} onClick={() => void remove()}>Remover link</Button></Dialog> : null}</section>;
}

function Row({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function projectLabel(value: string) { return ({ NOT_STARTED: "Não iniciado", IN_PROGRESS: "Em andamento", PAUSED: "Pausado", DELAYED: "Atrasado", COMPLETED: "Concluído", CANCELLED: "Cancelado" } as Record<string, string>)[value] ?? value; }
function projectTone(value: string): "success" | "warning" | "danger" | "neutral" { return value === "IN_PROGRESS" || value === "COMPLETED" ? "success" : value === "DELAYED" ? "danger" : value === "PAUSED" ? "warning" : "neutral"; }
