import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Badge, EmptyState, Input, Skeleton } from "../../components/ui.js";
import { Project, dateBR, portfolioApi } from "./api.js";

export function ProjectsPage() { const [projects, setProjects] = useState<Project[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL"); const [loading, setLoading] = useState(true); useEffect(() => { void portfolioApi.projects().then((result) => setProjects(result?.items ?? [])).finally(() => setLoading(false)); }, []); const items = useMemo(() => projects.filter((item) => (status === "ALL" || item.status === status) && `${item.name} ${item.client.name}`.toLowerCase().includes(query.toLowerCase())), [projects, query, status]); if (loading) return <><Skeleton /><Skeleton /></>; return <section><div className="page-heading"><div><p className="eyebrow">Projetos</p><h1>Portfólio de projetos</h1><p className="muted">Execução vinculada aos clientes e contratos canônicos.</p></div><Link className="ui-button ui-button-primary" to="/projects/new">+ Novo projeto</Link></div><div className="portfolio-kpis"><Metric label="Em andamento" value={String(projects.filter((item) => item.status === "IN_PROGRESS").length)} /><Metric label="Atrasados" value={String(projects.filter((item) => item.status === "DELAYED").length)} tone="danger" /><Metric label="Concluídos" value={String(projects.filter((item) => item.status === "COMPLETED").length)} /></div><div className="card portfolio-card"><div className="portfolio-toolbar"><Input aria-label="Buscar projetos" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar projeto ou cliente…" /><select className="ui-input project-filter" value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">Todos os status</option>{["NOT_STARTED", "IN_PROGRESS", "PAUSED", "DELAYED", "COMPLETED", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</select></div>{items.length ? <div className="table-scroll"><table className="portfolio-table"><thead><tr><th>Projeto</th><th>Contrato</th><th>Gerente</th><th>Status</th><th>Início</th><th>Previsão</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link className="table-primary" to={`/projects/${item.id}`}>{item.name}</Link><span>{item.client.name}</span></td><td>{item.contract ? <Link to={`/finance/contracts/${item.contract.id}`}>{item.contract.name}</Link> : "—"}</td><td>{item.manager?.name ?? "Não definido"}</td><td><Badge tone={projectTone(item.status)}>{projectLabel(item.status)}</Badge></td><td>{dateBR(item.startDate)}</td><td>{dateBR(item.expectedEndDate)}</td></tr>)}</tbody></table></div> : <EmptyState title="Nenhum projeto encontrado" detail="Crie um projeto ou ajuste os filtros." />}</div></section>; }
function Metric({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div className={`kpi ${tone ? `kpi-${tone}` : ""}`}><span className="muted">{label}</span><strong>{value}</strong></div>; }
function projectLabel(value: string) { return ({ NOT_STARTED: "Não iniciado", IN_PROGRESS: "Em andamento", PAUSED: "Pausado", DELAYED: "Atrasado", COMPLETED: "Concluído", CANCELLED: "Cancelado" } as Record<string, string>)[value] ?? value; }
function projectTone(value: string): "success" | "warning" | "danger" | "neutral" { return value === "IN_PROGRESS" || value === "COMPLETED" ? "success" : value === "DELAYED" ? "danger" : value === "PAUSED" ? "warning" : "neutral"; }
