import { ClientType, ContractProduct, ContractStatus, Prisma, PrismaClient, ProjectStatus, ResourceLinkType } from "@prisma/client";
import { Context, Hono } from "hono";
import { MoneyBRL } from "../../finance-contract-receivables/domain/MoneyBRL.js";
import { FinanceCapability } from "../../finance-contract-receivables/application/FinanceCapability.js";
import { FinanceAuthenticator, FinanceEnv, authenticationMiddleware, capabilityMiddleware, idempotencyKey } from "../../finance-contract-receivables/http/financeCommandMiddleware.js";

export interface PortfolioRouteDependencies { readonly prisma: PrismaClient; readonly authenticate: FinanceAuthenticator; }
const clientTypes = new Set<ClientType>(["PERSON", "COMPANY"]);
const contractProducts = new Set<ContractProduct>(["START", "LOOP", "NEXT", "OTHER"]);
const contractStatuses = new Set<ContractStatus>(["ACTIVE", "COMPLETED", "PAUSED", "CANCELLED"]);
const projectStatuses = new Set<ProjectStatus>(["NOT_STARTED", "IN_PROGRESS", "PAUSED", "DELAYED", "COMPLETED", "CANCELLED"]);
const linkTypes = new Set<ResourceLinkType>(["CONTRACT", "PROPOSAL", "SCOPE", "AMENDMENT", "INVOICE", "RECEIPT", "DRIVE", "FIGMA", "NOTION", "REPOSITORY", "PRODUCTION", "STAGING", "DOCUMENTATION", "OTHER"]);

function error(context: Context<FinanceEnv>, status: 400 | 404 | 409 | 422, code: string) { return context.json({ error: { code, message: code } }, status); }
function requireIntent(context: Context<FinanceEnv>) { try { return idempotencyKey(context); } catch { return undefined; } }
async function body(context: Context<FinanceEnv>): Promise<Record<string, unknown> | undefined> { try { const value = await context.req.json(); return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : undefined; } catch { return undefined; } }
function text(value: unknown, required = false): string | undefined { if (value === undefined || value === null || value === "") return required ? undefined : undefined; return typeof value === "string" ? value.trim() || (required ? undefined : undefined) : undefined; }
function nullableText(value: unknown): string | null | undefined { if (value === null || value === "") return null; return typeof value === "string" ? value.trim() || null : undefined; }
function bool(value: unknown): boolean | undefined { return typeof value === "boolean" ? value : undefined; }
function positiveInt(value: unknown): number | null | undefined { if (value === null || value === "") return null; return typeof value === "number" && Number.isInteger(value) && value >= 0 ? value : undefined; }
function date(value: unknown): Date | null | undefined { if (value === null || value === "") return null; if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined; const result = new Date(`${value}T00:00:00.000Z`); return Number.isNaN(result.getTime()) ? undefined : result; }
function dateText(value: Date | null): string | null { return value ? value.toISOString().slice(0, 10) : null; }
function money(value: unknown): bigint | undefined { if (typeof value !== "string") return undefined; try { return MoneyBRL.parse(value, { positive: true }).cents; } catch { return undefined; } }
function moneyText(value: bigint): string { return MoneyBRL.fromCents(value).toApi(); }
function enumValue<T extends string>(value: unknown, allowed: ReadonlySet<T>): T | undefined { return typeof value === "string" && allowed.has(value as T) ? value as T : undefined; }
function linkPayload(value: Record<string, unknown>) { const type = enumValue(value.type, linkTypes); const label = text(value.label, true); const url = text(value.url, true); const description = nullableText(value.description); try { if (!url || !/^https?:\/\//.test(url)) return undefined; } catch { return undefined; } return type && label && url && description !== undefined ? { type, label, url, description } : undefined; }
function audit(prisma: PrismaClient, actorUserId: string, action: string, aggregateType: string, aggregateId: string, contractId?: string) { return prisma.auditEvent.create({ data: { domain: "portfolio", action, aggregateType, aggregateId, contractId: contractId ?? null, actorUserId, context: {} } }); }
function serializeClient(client: { id: string; name: string; type: ClientType; documentNumber: string | null; email: string | null; phone: string | null; financialContactName: string | null; financialContactEmail: string | null; financialContactPhone: string | null; notes: string | null; createdAt: Date; updatedAt: Date }) { return { ...client, createdAt: client.createdAt.toISOString(), updatedAt: client.updatedAt.toISOString() }; }
function serializeLink(link: { id: string; type: ResourceLinkType; label: string; url: string; description: string | null; createdAt: Date }) { return { ...link, createdAt: link.createdAt.toISOString() }; }

function paymentSummary(plans: readonly { totalCents: bigint; status: string; installments: readonly { originalCents: bigint; dueDate: Date; allocations: readonly { transaction: { type: string }; amountCents: bigint }[] }[]; transactions: readonly { type: string; amountCents: bigint }[] }[]) {
  const today = new Date().toISOString().slice(0, 10); const monthKey = today.slice(0, 7); let received = 0n; let overdue = 0n; let forecastThisMonth = 0n; let nextDue: string | null = null; let installments = 0;
  for (const plan of plans) {
    for (const transaction of plan.transactions) received += transaction.type === "RECEIPT" ? transaction.amountCents : -transaction.amountCents;
    for (const installment of plan.installments) {
      installments += 1; let settled = 0n;
      for (const allocation of installment.allocations) settled += allocation.transaction.type === "RECEIPT" ? allocation.amountCents : -allocation.amountCents;
      const balance = installment.originalCents - settled; const due = dateText(installment.dueDate)!;
      if (balance > 0n && due < today) overdue += balance;
      if (balance > 0n && due.slice(0, 7) === monthKey) forecastThisMonth += balance;
      if (balance > 0n && due >= today && (!nextDue || due < nextDue)) nextDue = due;
    }
  }
  const total = plans.length ? plans[0]!.totalCents : 0n;
  return { hasPlan: plans.length > 0, planStatus: plans[0]?.status ?? null, total, received, outstanding: total > received ? total - received : 0n, overdue, forecastThisMonth, installments, nextDue };
}

export function registerPortfolioRoutes(app: Hono<FinanceEnv>, dependencies: PortfolioRouteDependencies): void {
  const { prisma, authenticate } = dependencies;
  app.use("/api/portfolio/*", authenticationMiddleware(authenticate));
  app.use("/api/dashboard", authenticationMiddleware(authenticate));

  app.get("/api/portfolio/clients", capabilityMiddleware("CLIENT_READ"), async (c) => {
    const query = c.req.query("q")?.trim(); const where: Prisma.ClientWhereInput = query ? { name: { contains: query, mode: "insensitive" } } : {}; const clients = await prisma.client.findMany({ where, orderBy: { name: "asc" }, take: 50 });
    return c.json({ items: clients.map(serializeClient) });
  });
  app.get("/api/portfolio/clients/:clientId", capabilityMiddleware("CLIENT_READ"), async (c) => { const client = await prisma.client.findUnique({ where: { id: c.req.param("clientId") } }); return client ? c.json(serializeClient(client)) : error(c, 404, "CLIENT_NOT_FOUND"); });
  app.post("/api/portfolio/clients", capabilityMiddleware("CLIENT_CREATE"), async (c) => {
    const payload = await body(c); const type = enumValue(payload?.type, clientTypes); const name = text(payload?.name, true); const actor = c.get("financeActor").actorUserId;
    if (!payload || !type || !name) return error(c, 422, "INVALID_CLIENT");
    try { idempotencyKey(c); } catch { return error(c, 422, "INVALID_IDEMPOTENCY_KEY"); }
    const client = await prisma.client.create({ data: { name, type, documentNumber: nullableText(payload.documentNumber) ?? null, email: nullableText(payload.email) ?? null, phone: nullableText(payload.phone) ?? null, financialContactName: nullableText(payload.financialContactName) ?? null, financialContactEmail: nullableText(payload.financialContactEmail) ?? null, financialContactPhone: nullableText(payload.financialContactPhone) ?? null, notes: nullableText(payload.notes) ?? null } });
    await audit(prisma, actor, "CLIENT_CREATED", "Client", client.id); return c.json(serializeClient(client), 201);
  });
  app.patch("/api/portfolio/clients/:clientId", capabilityMiddleware("CLIENT_EDIT"), async (c) => {
    if (!requireIntent(c)) return error(c, 422, "INVALID_IDEMPOTENCY_KEY");
    const payload = await body(c); if (!payload) return error(c, 422, "INVALID_CLIENT"); const type = payload.type === undefined ? undefined : enumValue(payload.type, clientTypes); if (payload.type !== undefined && !type) return error(c, 422, "INVALID_CLIENT");
    const data: Prisma.ClientUpdateInput = {};
    const name = text(payload.name, true); if (name) data.name = name;
    if (type) data.type = type;
    if (payload.documentNumber !== undefined) { const value = nullableText(payload.documentNumber); if (value !== undefined) data.documentNumber = value; }
    if (payload.email !== undefined) { const value = nullableText(payload.email); if (value !== undefined) data.email = value; }
    if (payload.phone !== undefined) { const value = nullableText(payload.phone); if (value !== undefined) data.phone = value; }
    if (payload.financialContactName !== undefined) { const value = nullableText(payload.financialContactName); if (value !== undefined) data.financialContactName = value; }
    if (payload.financialContactEmail !== undefined) { const value = nullableText(payload.financialContactEmail); if (value !== undefined) data.financialContactEmail = value; }
    if (payload.financialContactPhone !== undefined) { const value = nullableText(payload.financialContactPhone); if (value !== undefined) data.financialContactPhone = value; }
    if (payload.notes !== undefined) { const value = nullableText(payload.notes); if (value !== undefined) data.notes = value; }
    try { const client = await prisma.client.update({ where: { id: c.req.param("clientId") }, data }); await audit(prisma, c.get("financeActor").actorUserId, "CLIENT_UPDATED", "Client", client.id); return c.json(serializeClient(client)); } catch { return error(c, 404, "CLIENT_NOT_FOUND"); }
  });

  app.get("/api/portfolio/contracts", capabilityMiddleware("CONTRACT_READ"), async (c) => {
    const q = c.req.query("q")?.trim(); const status = c.req.query("status"); const contracts = await prisma.contract.findMany({ where: { ...(status && contractStatuses.has(status as ContractStatus) ? { status: status as ContractStatus } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { client: { name: { contains: q, mode: "insensitive" } } }] } : {}) }, include: { client: true, project: true }, orderBy: { updatedAt: "desc" } });
    const plans = await prisma.paymentPlan.findMany({ where: { contractId: { in: contracts.map((item) => item.id) }, discardedAt: null }, include: { installments: { include: { allocations: { include: { transaction: true } } } }, transactions: true } }); const plansByContract = new Map(plans.map((plan) => [plan.contractId, [plan]]));
    return c.json({ items: contracts.map((contract) => { const summary = paymentSummary(plansByContract.get(contract.id) ?? []); return { id: contract.id, name: contract.name, client: { id: contract.client.id, name: contract.client.name }, product: contract.product, customProductName: contract.customProductName, status: contract.status, value: moneyText(contract.contractValueCents), received: moneyText(summary.received), outstanding: moneyText(summary.outstanding), overdue: moneyText(summary.overdue), installments: summary.installments, nextDue: summary.nextDue, hasPlan: summary.hasPlan, planStatus: summary.planStatus, project: contract.project ? { id: contract.project.id, name: contract.project.name } : null }; }) });
  });
  app.post("/api/portfolio/contracts", capabilityMiddleware("CONTRACT_CREATE_MANUAL"), async (c) => {
    const payload = await body(c); if (!payload) return error(c, 422, "INVALID_CONTRACT"); const name = text(payload.name, true); const clientId = text(payload.clientId, true); const product = enumValue(payload.product, contractProducts); const status = enumValue(payload.status ?? "ACTIVE", contractStatuses); const value = money(payload.contractValue); const customProductName = nullableText(payload.customProductName); const signatureDate = date(payload.signatureDate); const startDate = date(payload.startDate); const expectedEndDate = date(payload.expectedEndDate); const term = positiveInt(payload.executionTermMonths); const shared = bool(payload.sharedProject ?? false);
    if (!name || !clientId || !product || !status || value === undefined || customProductName === undefined || signatureDate === undefined || startDate === undefined || expectedEndDate === undefined || term === undefined || shared === undefined || (product === "OTHER" && !customProductName)) return error(c, 422, "INVALID_CONTRACT");
    try { idempotencyKey(c); } catch { return error(c, 422, "INVALID_IDEMPOTENCY_KEY"); }
    try { const contract = await prisma.contract.create({ data: { name, clientId, product, status, contractValueCents: value, customProductName, signatureDate, startDate, expectedEndDate, executionTermMonths: term, description: nullableText(payload.description) ?? null, internalNotes: nullableText(payload.internalNotes) ?? null, sharedProject: shared, partnerName: shared ? nullableText(payload.partnerName) ?? null : null, transferRule: shared ? nullableText(payload.transferRule) ?? null : null, createdByUserId: c.get("financeActor").actorUserId }, include: { client: true, project: true, links: true } }); await audit(prisma, c.get("financeActor").actorUserId, "CONTRACT_MANUAL_INTAKE_CREATED", "Contract", contract.id, contract.id); return c.json(serializeContract(contract, paymentSummary([])), 201); } catch { return error(c, 422, "CLIENT_NOT_FOUND"); }
  });
  app.get("/api/portfolio/contracts/:contractId/history", capabilityMiddleware("CONTRACT_READ"), async (c) => {
    const events = await prisma.auditEvent.findMany({ where: { contractId: c.req.param("contractId") }, orderBy: { occurredAt: "desc" }, take: 100 });
    return c.json({ items: events.map((event) => ({ id: event.id, action: event.action, aggregateType: event.aggregateType, aggregateId: event.aggregateId, occurredAt: event.occurredAt.toISOString(), reason: event.reason, context: event.context })) });
  });
  app.get("/api/portfolio/contracts/:contractId", capabilityMiddleware("CONTRACT_READ"), async (c) => {
    const contract = await prisma.contract.findUnique({ where: { id: c.req.param("contractId") }, include: { client: true, project: true, links: { orderBy: { createdAt: "desc" } } } }); if (!contract) return error(c, 404, "CONTRACT_NOT_FOUND"); const plans = await prisma.paymentPlan.findMany({ where: { contractId: contract.id, discardedAt: null }, include: { installments: { include: { allocations: { include: { transaction: true } } } }, transactions: true } }); return c.json(serializeContract(contract, paymentSummary(plans)));
  });
  app.patch("/api/portfolio/contracts/:contractId", capabilityMiddleware("CONTRACT_EDIT"), async (c) => {
    if (!requireIntent(c)) return error(c, 422, "INVALID_IDEMPOTENCY_KEY");
    const payload = await body(c); if (!payload) return error(c, 422, "INVALID_CONTRACT"); const product = payload.product === undefined ? undefined : enumValue(payload.product, contractProducts); const status = payload.status === undefined ? undefined : enumValue(payload.status, contractStatuses); const value = payload.contractValue === undefined ? undefined : money(payload.contractValue); if ((payload.product !== undefined && !product) || (payload.status !== undefined && !status) || (payload.contractValue !== undefined && value === undefined)) return error(c, 422, "INVALID_CONTRACT");
    const data: Prisma.ContractUpdateInput = {};
    const name = text(payload.name, true); if (name) data.name = name;
    if (product) data.product = product;
    if (status) data.status = status;
    if (value !== undefined) data.contractValueCents = value;
    if (payload.customProductName !== undefined) { const item = nullableText(payload.customProductName); if (item !== undefined) data.customProductName = item; }
    for (const [key, raw] of [["signatureDate", payload.signatureDate], ["startDate", payload.startDate], ["expectedEndDate", payload.expectedEndDate]] as const) {
      if (raw !== undefined) { const parsed = date(raw); if (parsed === undefined) return error(c, 422, "INVALID_CONTRACT_DATE"); data[key] = parsed; }
    }
    if (payload.executionTermMonths !== undefined) { const item = positiveInt(payload.executionTermMonths); if (item === undefined) return error(c, 422, "INVALID_CONTRACT_TERM"); data.executionTermMonths = item; }
    if (payload.description !== undefined) { const item = nullableText(payload.description); if (item !== undefined) data.description = item; }
    if (payload.internalNotes !== undefined) { const item = nullableText(payload.internalNotes); if (item !== undefined) data.internalNotes = item; }
    if (payload.sharedProject !== undefined) { const item = bool(payload.sharedProject); if (item === undefined) return error(c, 422, "INVALID_CONTRACT"); data.sharedProject = item; }
    if (payload.partnerName !== undefined) { const item = nullableText(payload.partnerName); if (item !== undefined) data.partnerName = item; }
    if (payload.transferRule !== undefined) { const item = nullableText(payload.transferRule); if (item !== undefined) data.transferRule = item; }
    try { const contract = await prisma.contract.update({ where: { id: c.req.param("contractId") }, data, include: { client: true, project: true, links: true } }); await audit(prisma, c.get("financeActor").actorUserId, "CONTRACT_UPDATED", "Contract", contract.id, contract.id); return c.json(serializeContract(contract, paymentSummary([]))); } catch { return error(c, 404, "CONTRACT_NOT_FOUND"); }
  });
  app.post("/api/portfolio/contracts/:contractId/links", capabilityMiddleware("RESOURCE_LINK_CREATE"), async (c) => { if (!requireIntent(c)) return error(c, 422, "INVALID_IDEMPOTENCY_KEY"); const payload = await body(c); const link = payload && linkPayload(payload); if (!link) return error(c, 422, "INVALID_LINK"); const contract = await prisma.contract.findUnique({ where: { id: c.req.param("contractId") } }); if (!contract) return error(c, 404, "CONTRACT_NOT_FOUND"); const created = await prisma.resourceLink.create({ data: { entityType: "CONTRACT", contractId: contract.id, ...link, createdByUserId: c.get("financeActor").actorUserId } }); await audit(prisma, c.get("financeActor").actorUserId, "RESOURCE_LINK_CREATED", "ResourceLink", created.id, contract.id); return c.json(serializeLink(created), 201); });
  app.patch("/api/portfolio/links/:linkId", capabilityMiddleware("RESOURCE_LINK_EDIT"), async (c) => { if (!requireIntent(c)) return error(c, 422, "INVALID_IDEMPOTENCY_KEY"); const payload = await body(c); const link = payload && linkPayload(payload); if (!link) return error(c, 422, "INVALID_LINK"); try { const updated = await prisma.resourceLink.update({ where: { id: c.req.param("linkId") }, data: link }); await audit(prisma, c.get("financeActor").actorUserId, "RESOURCE_LINK_UPDATED", "ResourceLink", updated.id, updated.contractId ?? undefined); return c.json(serializeLink(updated)); } catch { return error(c, 404, "RESOURCE_LINK_NOT_FOUND"); } });
  app.delete("/api/portfolio/links/:linkId", capabilityMiddleware("RESOURCE_LINK_DELETE"), async (c) => { if (!requireIntent(c)) return error(c, 422, "INVALID_IDEMPOTENCY_KEY"); try { const removed = await prisma.resourceLink.delete({ where: { id: c.req.param("linkId") } }); await audit(prisma, c.get("financeActor").actorUserId, "RESOURCE_LINK_DELETED", "ResourceLink", removed.id, removed.contractId ?? undefined); return c.body(null, 204); } catch { return error(c, 404, "RESOURCE_LINK_NOT_FOUND"); } });

  app.get("/api/portfolio/members", capabilityMiddleware("PROJECT_READ"), async (c) => { const members = await prisma.member.findMany({ include: { user: { select: { name: true } } }, orderBy: { user: { name: "asc" } } }); return c.json({ items: members.map((member) => ({ id: member.id, name: member.user.name })) }); });
  app.get("/api/portfolio/projects", capabilityMiddleware("PROJECT_READ"), async (c) => { const q = c.req.query("q")?.trim(); const status = c.req.query("status"); const projects = await prisma.project.findMany({ where: { ...(status && projectStatuses.has(status as ProjectStatus) ? { status: status as ProjectStatus } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { client: { name: { contains: q, mode: "insensitive" } } }] } : {}) }, include: { client: true, contract: true, manager: { include: { user: true } } }, orderBy: { updatedAt: "desc" } }); return c.json({ items: projects.map(serializeProject) }); });
  app.post("/api/portfolio/projects", capabilityMiddleware("PROJECT_CREATE"), async (c) => { if (!requireIntent(c)) return error(c, 422, "INVALID_IDEMPOTENCY_KEY"); const payload = await body(c); if (!payload) return error(c, 422, "INVALID_PROJECT"); const name = text(payload.name, true); const clientId = text(payload.clientId, true); const status = enumValue(payload.status ?? "NOT_STARTED", projectStatuses); const contractId = nullableText(payload.contractId); const managerMemberId = nullableText(payload.managerMemberId); const startDate = date(payload.startDate); const expectedEndDate = date(payload.expectedEndDate); if (!name || !clientId || !status || contractId === undefined || managerMemberId === undefined || startDate === undefined || expectedEndDate === undefined) return error(c, 422, "INVALID_PROJECT");
    if (contractId) {
      const contract = await prisma.contract.findUnique({ where: { id: contractId }, select: { clientId: true } });
      if (!contract || contract.clientId !== clientId) return error(c, 422, "INVALID_PROJECT_REFERENCE");
    }
    try { const project = await prisma.project.create({ data: { name, clientId, status, contractId, managerMemberId, startDate, expectedEndDate, description: nullableText(payload.description) ?? null, internalNotes: nullableText(payload.internalNotes) ?? null }, include: { client: true, contract: true, manager: { include: { user: true } } } }); await audit(prisma, c.get("financeActor").actorUserId, "PROJECT_CREATED", "Project", project.id, project.contractId ?? undefined); return c.json(serializeProject(project), 201); } catch { return error(c, 422, "INVALID_PROJECT_REFERENCE"); } });
  app.patch("/api/portfolio/projects/:projectId", capabilityMiddleware("PROJECT_EDIT"), async (c) => {
    if (!requireIntent(c)) return error(c, 422, "INVALID_IDEMPOTENCY_KEY");
    const payload = await body(c); if (!payload) return error(c, 422, "INVALID_PROJECT");
    const data: Prisma.ProjectUpdateInput = {};
    const name = text(payload.name, true); if (name) data.name = name;
    if (payload.status !== undefined) { const status = enumValue(payload.status, projectStatuses); if (!status) return error(c, 422, "INVALID_PROJECT"); data.status = status; }
    if (payload.clientId !== undefined) { const clientId = text(payload.clientId, true); if (!clientId) return error(c, 422, "INVALID_PROJECT"); data.client = { connect: { id: clientId } }; }
    if (payload.contractId !== undefined) { const contractId = nullableText(payload.contractId); if (contractId === undefined) return error(c, 422, "INVALID_PROJECT"); data.contract = contractId ? { connect: { id: contractId } } : { disconnect: true }; }
    if (payload.managerMemberId !== undefined) { const managerId = nullableText(payload.managerMemberId); if (managerId === undefined) return error(c, 422, "INVALID_PROJECT"); data.manager = managerId ? { connect: { id: managerId } } : { disconnect: true }; }
    for (const [key, raw] of [["startDate", payload.startDate], ["expectedEndDate", payload.expectedEndDate]] as const) { if (raw !== undefined) { const parsed = date(raw); if (parsed === undefined) return error(c, 422, "INVALID_PROJECT_DATE"); data[key] = parsed; } }
    if (payload.description !== undefined) { const value = nullableText(payload.description); if (value !== undefined) data.description = value; }
    if (payload.internalNotes !== undefined) { const value = nullableText(payload.internalNotes); if (value !== undefined) data.internalNotes = value; }
    const current = await prisma.project.findUnique({ where: { id: c.req.param("projectId") }, select: { clientId: true, contractId: true } });
    if (!current) return error(c, 404, "PROJECT_NOT_FOUND");
    const nextClientId = payload.clientId === undefined ? current.clientId : text(payload.clientId, true);
    const nextContractId = payload.contractId === undefined ? current.contractId : nullableText(payload.contractId);
    if (!nextClientId || nextContractId) {
      const contract = nextContractId ? await prisma.contract.findUnique({ where: { id: nextContractId }, select: { clientId: true } }) : null;
      if (nextContractId && (!contract || contract.clientId !== nextClientId)) return error(c, 422, "INVALID_PROJECT_REFERENCE");
    }
    try { const project = await prisma.project.update({ where: { id: c.req.param("projectId") }, data, include: { client: true, contract: true, manager: { include: { user: true } } } }); await audit(prisma, c.get("financeActor").actorUserId, "PROJECT_UPDATED", "Project", project.id, project.contractId ?? undefined); return c.json(serializeProject(project)); } catch { return error(c, 404, "PROJECT_NOT_FOUND"); }
  });
  app.get("/api/portfolio/projects/:projectId", capabilityMiddleware("PROJECT_READ"), async (c) => { const project = await prisma.project.findUnique({ where: { id: c.req.param("projectId") }, include: { client: true, contract: true, manager: { include: { user: true } }, links: { orderBy: { createdAt: "desc" } } } }); if (!project) return error(c, 404, "PROJECT_NOT_FOUND"); const plans = project.contractId ? await prisma.paymentPlan.findMany({ where: { contractId: project.contractId, discardedAt: null }, include: { installments: { include: { allocations: { include: { transaction: true } } } }, transactions: true } }) : []; const summary = paymentSummary(plans); return c.json({ ...serializeProject(project), links: project.links.map(serializeLink), finance: project.contract ? { value: moneyText(project.contract.contractValueCents), received: moneyText(summary.received), outstanding: moneyText(summary.outstanding), overdue: moneyText(summary.overdue), nextDue: summary.nextDue } : null }); });
  app.post("/api/portfolio/projects/:projectId/links", capabilityMiddleware("RESOURCE_LINK_CREATE"), async (c) => { if (!requireIntent(c)) return error(c, 422, "INVALID_IDEMPOTENCY_KEY"); const payload = await body(c); const link = payload && linkPayload(payload); if (!link) return error(c, 422, "INVALID_LINK"); const project = await prisma.project.findUnique({ where: { id: c.req.param("projectId") } }); if (!project) return error(c, 404, "PROJECT_NOT_FOUND"); const created = await prisma.resourceLink.create({ data: { entityType: "PROJECT", projectId: project.id, ...link, createdByUserId: c.get("financeActor").actorUserId } }); await audit(prisma, c.get("financeActor").actorUserId, "RESOURCE_LINK_CREATED", "ResourceLink", created.id, project.contractId ?? undefined); return c.json(serializeLink(created), 201); });

  app.get("/api/dashboard", capabilityMiddleware("DASHBOARD_READ"), async (c) => { const contracts = await prisma.contract.findMany({ include: { client: true, project: true, links: true } }); const projects = await prisma.project.findMany({ include: { client: true, contract: true, manager: { include: { user: true } } } }); const plans = await prisma.paymentPlan.findMany({ where: { discardedAt: null }, include: { installments: { include: { allocations: { include: { transaction: true } } } }, transactions: true } }); const byContract = new Map<string, typeof plans>(); for (const plan of plans) byContract.set(plan.contractId, [...(byContract.get(plan.contractId) ?? []), plan]); let contracted = 0n; let received = 0n; let outstanding = 0n; let overdue = 0n; const attention: { kind: string; label: string; contractId?: string; projectId?: string }[] = [];
    let forecastThisMonth = 0n;
    for (const contract of contracts) { contracted += contract.contractValueCents; const summary = paymentSummary(byContract.get(contract.id) ?? []); received += summary.received; outstanding += summary.outstanding; overdue += summary.overdue; forecastThisMonth += summary.forecastThisMonth; if (contract.status === "ACTIVE" && !summary.hasPlan) attention.push({ kind: "SEM_PLANO", label: `${contract.name} não possui plano de pagamento`, contractId: contract.id }); if (!contract.links.some((link) => link.type === "CONTRACT")) attention.push({ kind: "SEM_DOCUMENTO", label: `${contract.name} não possui contrato assinado vinculado`, contractId: contract.id }); if (summary.planStatus === "DRAFT") attention.push({ kind: "PLANO_RASCUNHO", label: `${contract.name} possui plano em rascunho`, contractId: contract.id }); if (summary.overdue > 0n) attention.push({ kind: "VENCIDO", label: `${contract.name} possui parcela vencida`, contractId: contract.id }); if (summary.outstanding > 0n && !summary.nextDue) attention.push({ kind: "SEM_VENCIMENTO_FUTURO", label: `${contract.name} tem saldo sem vencimento futuro`, contractId: contract.id }); }
    for (const project of projects) { if (project.status === "DELAYED") attention.push({ kind: "PROJETO_ATRASADO", label: `${project.name} está atrasado`, projectId: project.id }); if (project.status === "IN_PROGRESS" && !project.managerMemberId) attention.push({ kind: "SEM_GERENTE", label: `${project.name} não possui gerente`, projectId: project.id }); }
    const upcoming = contracts.flatMap((contract) => { const plan = paymentSummary(byContract.get(contract.id) ?? []); return plan.nextDue ? [{ contractId: contract.id, contract: contract.name, client: contract.client.name, dueDate: plan.nextDue, outstanding: moneyText(plan.outstanding) }] : []; }).sort((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 8);
    return c.json({ contracts: { active: contracts.filter((item) => item.status === "ACTIVE").length, completed: contracts.filter((item) => item.status === "COMPLETED").length }, projects: { active: projects.filter((item) => item.status === "IN_PROGRESS").length, delayed: projects.filter((item) => item.status === "DELAYED").length }, finance: { contracted: moneyText(contracted), received: moneyText(received), outstanding: moneyText(outstanding), overdue: moneyText(overdue), forecastThisMonth: moneyText(forecastThisMonth) }, upcomingInstallments: upcoming, attentionItems: attention.slice(0, 8), activeProjects: projects.filter((item) => item.status === "IN_PROGRESS").slice(0, 6).map(serializeProject) }); });
}

function serializeContract(contract: { id: string; name: string; origin: string; status: ContractStatus; product: ContractProduct; customProductName: string | null; contractValueCents: bigint; signatureDate: Date | null; startDate: Date | null; expectedEndDate: Date | null; executionTermMonths: number | null; description: string | null; internalNotes: string | null; sharedProject: boolean; partnerName: string | null; transferRule: string | null; createdAt: Date; updatedAt: Date; client: { id: string; name: string; type: ClientType; documentNumber: string | null; email: string | null; phone: string | null; financialContactName: string | null; financialContactEmail: string | null; financialContactPhone: string | null; notes: string | null; createdAt: Date; updatedAt: Date }; project: { id: string; name: string } | null; links: readonly { id: string; type: ResourceLinkType; label: string; url: string; description: string | null; createdAt: Date }[] }, summary: ReturnType<typeof paymentSummary>) { return { id: contract.id, name: contract.name, origin: contract.origin, status: contract.status, product: contract.product, customProductName: contract.customProductName, contractValue: moneyText(contract.contractValueCents), signatureDate: dateText(contract.signatureDate), startDate: dateText(contract.startDate), expectedEndDate: dateText(contract.expectedEndDate), executionTermMonths: contract.executionTermMonths, description: contract.description, internalNotes: contract.internalNotes, sharedProject: contract.sharedProject, partnerName: contract.partnerName, transferRule: contract.transferRule, client: serializeClient(contract.client), project: contract.project, links: contract.links.map(serializeLink), finance: { hasPlan: summary.hasPlan, planStatus: summary.planStatus, received: moneyText(summary.received), outstanding: moneyText(summary.outstanding), overdue: moneyText(summary.overdue), nextDue: summary.nextDue, installments: summary.installments }, createdAt: contract.createdAt.toISOString(), updatedAt: contract.updatedAt.toISOString() }; }
function serializeProject(project: { id: string; name: string; status: ProjectStatus; startDate: Date | null; expectedEndDate: Date | null; description?: string | null; internalNotes?: string | null; createdAt: Date; updatedAt: Date; client: { id: string; name: string }; contract: { id: string; name: string } | null; manager: { id: string; user: { name: string } } | null }) { return { id: project.id, name: project.name, status: project.status, startDate: dateText(project.startDate), expectedEndDate: dateText(project.expectedEndDate), description: project.description ?? null, internalNotes: project.internalNotes ?? null, client: project.client, contract: project.contract, manager: project.manager ? { id: project.manager.id, name: project.manager.user.name } : null, createdAt: project.createdAt.toISOString(), updatedAt: project.updatedAt.toISOString() }; }
