import { PrismaClient } from "@prisma/client";
import { afterAll, describe, expect, it } from "vitest";
import { createApp } from "../../../../app.js";
import { ActivatePaymentPlan } from "../../application/ActivatePaymentPlan.js";
import { ChangeDraftPlanTotal } from "../../application/ChangeDraftPlanTotal.js";
import { CreateInstallment } from "../../application/CreateInstallment.js";
import { CreatePaymentPlan } from "../../application/CreatePaymentPlan.js";
import { DiscardPaymentPlan } from "../../application/DiscardPaymentPlan.js";
import { EditDraftInstallment } from "../../application/EditDraftInstallment.js";
import { FixtureContractReferencePort, ReceivablesContractContext } from "../../application/ContractReferencePort.js";
import { FinanceCommandExecutor } from "../../application/FinanceCommandExecutor.js";
import { AuthenticatedCommandContext, InMemoryAuthorizationPort, gerenteFinanceiroCapabilities, vicePresidenteCapabilities } from "../../application/FinanceCapability.js";
import { GetContractReceivables } from "../../application/GetContractReceivables.js";
import { GetFinancialAudit } from "../../application/GetFinancialAudit.js";
import { RegisterReceipt } from "../../application/RegisterReceipt.js";
import { RemoveDraftInstallment } from "../../application/RemoveDraftInstallment.js";
import { ReorderInstallments } from "../../application/ReorderInstallments.js";
import { ReturnPlanToDraft } from "../../application/ReturnPlanToDraft.js";
import { ReverseReceipt } from "../../application/ReverseReceipt.js";
import { LocalDate } from "../../domain/LocalDate.js";
import { MoneyBRL } from "../../domain/MoneyBRL.js";
import { PrismaFinanceUnitOfWork } from "../../infrastructure/PrismaFinanceUnitOfWork.js";
import { PrismaIdempotencyStore } from "../../infrastructure/PrismaIdempotencyStore.js";
import { PrismaPaymentPlanLookup } from "../../infrastructure/PrismaPaymentPlanLookup.js";
import { PrismaTransactionalAuditWriter } from "../../infrastructure/PrismaTransactionalAuditWriter.js";

const databaseUrl = process.env.DATABASE_URL_TEST; if (!databaseUrl) throw new Error("DATABASE_URL_TEST required");
const prisma = new PrismaClient({ datasources: { db: { url: databaseUrl } } }); const contracts = new Map<string, ReceivablesContractContext>(); const contractPort = new FixtureContractReferencePort(contracts);
const adminCapabilities = new Set<never>(); const authorization = new InMemoryAuthorizationPort(new Map([["manager", gerenteFinanceiroCapabilities], ["vp", vicePresidenteCapabilities], ["admin", adminCapabilities]]));
const unit = new PrismaFinanceUnitOfWork(prisma); const executor = new FinanceCommandExecutor(authorization, unit, new PrismaIdempotencyStore(prisma)); const audit = new PrismaTransactionalAuditWriter();
const actors: Record<string, AuthenticatedCommandContext> = { manager: { actorUserId: "manager", capabilities: gerenteFinanceiroCapabilities }, vp: { actorUserId: "vp", capabilities: vicePresidenteCapabilities }, admin: { actorUserId: "admin", capabilities: adminCapabilities } };
const app = createApp({ authenticate: async (request) => actors[request.headers.get("Authorization")?.replace("Bearer ", "") ?? ""], createPlan: new CreatePaymentPlan(contractPort, authorization, executor, audit), changeTotal: new ChangeDraftPlanTotal(authorization, executor, audit), createInstallment: new CreateInstallment(authorization, executor, audit), editInstallment: new EditDraftInstallment(authorization, executor, audit), removeInstallment: new RemoveDraftInstallment(authorization, executor, audit), reorderInstallments: new ReorderInstallments(authorization, executor, audit), activatePlan: new ActivatePaymentPlan(authorization, executor, contractPort, new PrismaPaymentPlanLookup(prisma), audit), returnPlanToDraft: new ReturnPlanToDraft(authorization, executor, audit), discardPlan: new DiscardPaymentPlan(authorization, executor, audit), registerReceipt: new RegisterReceipt(authorization, executor, audit), reverseReceipt: new ReverseReceipt(authorization, executor, audit), getReceivables: new GetContractReceivables(prisma, authorization, contractPort, { todayIn: () => LocalDate.parse("2026-08-18") }), getAudit: new GetFinancialAudit(prisma, authorization) });
const key = () => `key-${crypto.randomUUID()}`; const headers = (actor: string, idempotency?: string) => ({ Authorization: `Bearer ${actor}`, "Content-Type": "application/json", ...(idempotency ? { "Idempotency-Key": idempotency } : {}) });
const send = (method: string, path: string, actor: string, body?: unknown, idempotency?: string) => app.request(path, { method, headers: headers(actor, idempotency), ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
afterAll(() => prisma.$disconnect());

describe("finance Hono API", () => {
  it("operates the complete receipt/reversal/read flow with bigint-safe DTOs", async () => {
    const contractId = `contract-${crypto.randomUUID()}`; contracts.set(contractId, { kind: "available", contractId, clientId: `client-${crypto.randomUUID()}`, currency: "BRL", financialValue: MoneyBRL.parse("1000.00"), eligibleForReceivables: true });
    const createKey = key(); let response = await send("POST", `/api/finance/contracts/${contractId}/payment-plans`, "manager", { totalAmount: "1000.00" }, createKey); expect(response.status).toBe(200); const plan = await response.json() as { id: string };
    response = await send("POST", `/api/finance/contracts/${contractId}/payment-plans`, "manager", { totalAmount: "1000.00" }, createKey); expect((await response.json() as { id: string }).id).toBe(plan.id);
    response = await send("POST", `/api/finance/payment-plans/${plan.id}/installments`, "manager", { originalAmount: "400.00", dueDate: "2026-08-01" }, key()); const firstInstallment = await response.json() as { id: string }; expect(response.status).toBe(200);
    response = await send("POST", `/api/finance/payment-plans/${plan.id}/installments`, "manager", { originalAmount: "600.00", dueDate: "2026-09-01" }, key()); const secondInstallment = await response.json() as { id: string }; expect(response.status).toBe(200);
    expect((await send("POST", `/api/finance/payment-plans/${plan.id}/activate`, "manager", undefined, key())).status).toBe(200);
    response = await send("POST", `/api/finance/payment-plans/${plan.id}/receipts`, "manager", { amount: "1000.00", allocations: [{ installmentId: firstInstallment.id, amount: "400.00" }, { installmentId: secondInstallment.id, amount: "600.00" }] }, key()); const receipt = await response.json() as { id: string; amount: string; allocations: { id: string; installmentId: string }[] }; expect(receipt.amount).toBe("1000.00");
    response = await send("POST", `/api/finance/financial-transactions/${receipt.id}/reversals`, "vp", { amount: "300.00", reason: "correction", allocations: [{ originalAllocationId: receipt.allocations[0]!.id, amount: "300.00" }] }, key()); expect(response.status).toBe(200);
    response = await send("POST", `/api/finance/payment-plans/${plan.id}/receipts`, "manager", { amount: "100.00", allocations: [{ installmentId: firstInstallment.id, amount: "100.00" }] }, key()); expect(response.status).toBe(200);
    response = await send("GET", `/api/finance/contracts/${contractId}/receivables`, "manager"); const viewText = await response.text(); expect(viewText).toContain('"remainingBalance":"200.00"'); expect(viewText).not.toMatch(/100000n/);
    expect((await send("GET", `/api/finance/contracts/${contractId}/receivables/audit`, "manager")).status).toBe(200);
  });
  it("enforces trusted auth, capabilities, closed DTOs, string money, timestamps and idempotency conflicts", async () => {
    expect((await app.request("/api/finance/contracts/x/receivables")).status).toBe(401);
    expect((await send("GET", "/api/finance/contracts/x/receivables", "admin")).status).toBe(403);
    expect((await send("POST", "/api/finance/contracts/x/payment-plans", "manager", { totalAmount: "1.00" })).status).toBe(422);
    expect((await send("POST", "/api/finance/contracts/x/payment-plans", "manager", { totalAmount: 1 }, key())).status).toBe(422);
    expect((await send("POST", "/api/finance/contracts/x/payment-plans", "manager", { totalAmount: "1.00", actorUserId: "vp" }, key())).status).toBe(422);
    expect((await send("POST", `/api/finance/payment-plans/${crypto.randomUUID()}/activate`, "manager", { status: "ACTIVE" }, key())).status).toBe(422);
    const forbiddenTimestamp = await send("POST", `/api/finance/payment-plans/${crypto.randomUUID()}/receipts`, "manager", { amount: "1.00", occurredAt: "2026-01-01T00:00:00Z", allocations: [] }, key()); expect(forbiddenTimestamp.status).toBe(422); expect((await forbiddenTimestamp.json() as { error: { code: string } }).error.code).toBe("CLIENT_OCCURRENCE_TIMESTAMP_FORBIDDEN");
    const contractId = `contract-${crypto.randomUUID()}`; contracts.set(contractId, { kind: "available", contractId, clientId: "client", currency: "BRL", financialValue: MoneyBRL.parse("10.00"), eligibleForReceivables: true }); const idem = key();
    expect((await send("POST", `/api/finance/contracts/${contractId}/payment-plans`, "manager", { totalAmount: "10.00" }, idem)).status).toBe(200);
    const conflict = await send("POST", `/api/finance/contracts/${contractId}/payment-plans`, "manager", { totalAmount: "9.00" }, idem); expect(conflict.status).toBe(409); expect(await conflict.text()).not.toContain("Prisma");
  });
  it("returns canonical no-plan references and bounded audit pages", async () => {
    const contractId = `contract-${crypto.randomUUID()}`; const clientId = `client-${crypto.randomUUID()}`;
    contracts.set(contractId, { kind: "available", contractId, clientId, currency: "BRL", financialValue: MoneyBRL.parse("25.00"), eligibleForReceivables: true });
    const noPlan = await send("GET", `/api/finance/contracts/${contractId}/receivables`, "manager");
    expect(noPlan.status).toBe(200); expect(await noPlan.json()).toMatchObject({ contractId, clientId, currency: "BRL", paymentPlan: null });
    expect((await send("GET", `/api/finance/contracts/${crypto.randomUUID()}/receivables`, "manager")).status).toBe(404);
    expect((await send("GET", `/api/finance/contracts/${contractId}/receivables/audit?limit=101`, "manager")).status).toBe(422);
    const audit = await send("GET", `/api/finance/contracts/${contractId}/receivables/audit?limit=1`, "manager");
    expect(audit.status).toBe(200); expect(await audit.json()).toMatchObject({ contractId, events: [], nextCursor: null });
  });
  it("exposes every explicit payment-plan and installment lifecycle route", async () => {
    const contractId = `contract-${crypto.randomUUID()}`; contracts.set(contractId, { kind: "available", contractId, clientId: `client-${crypto.randomUUID()}`, currency: "BRL", financialValue: MoneyBRL.parse("1000.00"), eligibleForReceivables: true });
    let response = await send("POST", `/api/finance/contracts/${contractId}/payment-plans`, "manager", { totalAmount: "1000.00" }, key()); const plan = await response.json() as { id: string };
    expect((await send("PATCH", `/api/finance/payment-plans/${plan.id}/draft-total`, "manager", { totalAmount: "1000.00" }, key())).status).toBe(200);
    response = await send("POST", `/api/finance/payment-plans/${plan.id}/installments`, "manager", { originalAmount: "400.00", dueDate: "2026-09-10" }, key()); const first = await response.json() as { id: string };
    response = await send("POST", `/api/finance/payment-plans/${plan.id}/installments`, "manager", { originalAmount: "600.00", dueDate: "2026-09-10" }, key()); const second = await response.json() as { id: string };
    response = await send("POST", `/api/finance/payment-plans/${plan.id}/installments`, "manager", { originalAmount: "1.00", dueDate: "2026-09-10" }, key()); const removable = await response.json() as { id: string };
    expect((await send("PATCH", `/api/finance/payment-plans/${plan.id}/installments/${first.id}`, "manager", { originalAmount: "450.00" }, key())).status).toBe(200);
    expect((await send("PATCH", `/api/finance/payment-plans/${plan.id}/installments/${second.id}`, "manager", { originalAmount: "550.00" }, key())).status).toBe(200);
    expect((await send("DELETE", `/api/finance/payment-plans/${plan.id}/installments/${removable.id}`, "manager", undefined, key())).status).toBe(200);
    expect((await send("POST", `/api/finance/payment-plans/${plan.id}/installments/reorder`, "manager", { installmentIds: [second.id, first.id] }, key())).status).toBe(200);
    const activationKey = key(); expect((await send("POST", `/api/finance/payment-plans/${plan.id}/activate`, "manager", undefined, activationKey)).status).toBe(200); expect((await send("POST", `/api/finance/payment-plans/${plan.id}/activate`, "manager", undefined, activationKey)).status).toBe(200);
    expect((await send("POST", `/api/finance/payment-plans/${plan.id}/return-to-draft`, "manager", { reason: "adjust" }, key())).status).toBe(403);
    expect((await send("POST", `/api/finance/payment-plans/${plan.id}/return-to-draft`, "vp", { reason: "adjust" }, key())).status).toBe(200);
    expect((await send("POST", `/api/finance/payment-plans/${plan.id}/discard`, "manager", { reason: "replace" }, key())).status).toBe(403);
    expect((await send("POST", `/api/finance/payment-plans/${plan.id}/discard`, "vp", { reason: "replace" }, key())).status).toBe(200);
    expect(await (await send("GET", `/api/finance/contracts/${contractId}/receivables`, "manager")).json()).toMatchObject({ paymentPlan: null });
    const firstAuditPage = await (await send("GET", `/api/finance/contracts/${contractId}/receivables/audit?limit=1`, "manager")).json() as { events: unknown[]; nextCursor: string };
    expect(firstAuditPage.events).toHaveLength(1); expect(firstAuditPage.nextCursor).toMatch(/^[0-9a-f-]{36}$/);
    expect((await send("GET", `/api/finance/contracts/${contractId}/receivables/audit?limit=1&cursor=${firstAuditPage.nextCursor}`, "manager")).status).toBe(200);
    expect((await send("POST", `/api/finance/contracts/${contractId}/payment-plans`, "manager", { totalAmount: "1000.00" }, key())).status).toBe(200);
  });
});
